version: "3.8"

services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
  
  app:
    depends_on:
      - mongodb
    build: ./pedidos_ms_db-app
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 3000:3000
    environment:
      - DB_HOST=mongodb
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=pedidos_ms_db
      - DB_PORT=27017
    stdin_open: true
    tty: true

volumes:
  db: