version: "3.7"

volumes:
  db:

services:
  mongodb:
    image: mongo:latest
    env_file: ./.env
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
    #   - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db
  
  pedidos-ms-app:
    depends_on:
      - mongodb
    build: .
    restart: always
    env_file: ./.env
    ports:
      - "3000:3000"
    # environment:
    #   - NODE_PORT=3000
    #   - DB_HOST=$MONGODB_HOST
    #   - DB_USER=$MONGODB_USER
    #   - DB_PASSWORD=$MONGODB_PASSWORD
    #   - DB_NAME=$MONGODB_DATABASE
    #   - DB_PORT=$MONGODB_DOCKER_PORT
    #   - MONGO_URI=mongodb://127.0.0.1:27017/pedidosdb
