version: "3.7"

volumes:
  db:

services:
  mongodb:
    image: mongo:latest
    command: mongod --port 27018
    ports:
      - "27018:27018"
    volumes:
      - db:/data/db
  
  pedidos-ms-app:
    depends_on:
      - mongodb
    build: .
    restart: always
    ports:
      - "3000:3000"
